INSERT INTO ACCOUNT("ID", "AMOUNT") VALUES ('1', 11.11)
INSERT INTO ACCOUNT("ID", "AMOUNT") VALUES ('2', 22.22)
INSERT INTO ACCOUNT("ID", "AMOUNT") VALUES ('3', 33.33)
INSERT INTO ACCOUNT("ID", "AMOUNT") VALUES ('4', 44.44)